# Generated by Django 4.2.1 on 2023-05-30 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_alter_post_center_x_alter_post_center_y'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='center_x',
            field=models.CharField(max_length=255, null=True, verbose_name='Координата 1'),
        ),
        migrations.AlterField(
            model_name='post',
            name='center_y',
            field=models.CharField(max_length=255, null=True, verbose_name='Координата 2'),
        ),
    ]
