# Generated by Django 4.2.1 on 2023-06-01 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0011_alter_commentnew_post_alter_commentnew_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentnew',
            name='body',
            field=models.TextField(verbose_name='Комментарий'),
        ),
    ]
