# Generated by Django 4.2.1 on 2023-06-16 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0016_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='scale',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Маштаб'),
        ),
    ]
