# Generated by Django 4.2.1 on 2023-06-24 07:34

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0018_post_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True, verbose_name='Видео'),
        ),
    ]
